Section 1 of:

https://www.udemy.com/deep-learning-prerequisites-the-numpy-stack-in-python/

https://deeplearningcourses.com/c/deep-learning-prerequisites-the-numpy-stack-in-python

## Arrays vs Lists

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
A.append(4) # doesn't work

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
L + [5]

[1, 2, 3, 4, 5]

In [10]:
A + np.array([4])

array([5, 6, 7])

In [11]:
A + np.array([4,5,6])

array([5, 7, 9])

In [12]:
A + np.array([4,5]) # doesn't work

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
2 * A

array([2, 4, 6])

In [14]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
L2 = []
for e in L:
  L2.append(e + 3)

In [17]:
L2

[4, 5, 6, 7]

In [18]:
L2 = [e + 3 for e in L]

In [19]:
L2

[4, 5, 6, 7]

In [20]:
L2 = []
for e in L:
  L2.append(e**2)

In [21]:
L2

[1, 4, 9, 16]

In [22]:
A**2

array([1, 4, 9])

In [23]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [24]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [27]:
a = np.array([1,2])
b = np.array([3,4])

In [28]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [29]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [30]:
a * b

array([3, 8])

In [31]:
np.sum(a * b)

11

In [32]:
(a * b).sum()

11

In [33]:
np.dot(a, b)

11

In [34]:
a.dot(b)

11

In [35]:
b.dot(a)

11

In [36]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [37]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [38]:
amag = np.linalg.norm(amag)
amag

2.23606797749979

In [39]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [40]:
cosangle

0.9838699100999074

In [41]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Speed Test

In [43]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 34.41550944485424


## Matrices

In [44]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [45]:
L[0]

[1, 2]

In [46]:
L[0][1]

2

In [47]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [48]:
A[0][1]

2

In [49]:
A[0,1]

2

In [50]:
A[:,0]

array([1, 3])

In [51]:
A.T

array([[1, 3],
       [2, 4]])

In [52]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [53]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [54]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [56]:
# error! inner dimensions must match
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [57]:
np.linalg.det(A)

-2.0000000000000004

In [58]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [59]:
np.linalg.inv(A).dot(A)

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [60]:
np.trace(A)

5

In [61]:
np.diag(A)

array([1, 4])

In [62]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [63]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [64]:
Lam, V = np.linalg.eig(A)

In [65]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [66]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [67]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [68]:
np.allclose(V @ np.diag(Lam), A @ V)

True

## Solving Linear Systems

In [69]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [70]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [71]:
# don't do this
np.linalg.inv(A).dot(b)

array([1500.,  700.])

## Generating Data

In [73]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.random.random()

0.6090871485527074

In [78]:
np.random.random((2, 3))

array([[0.62505705, 0.54099487, 0.85230376],
       [0.14499094, 0.87163074, 0.52876563]])

In [79]:
np.random.randn(2, 3)

array([[-0.92142737,  0.29994161,  1.68456069],
       [ 0.78509225,  1.79713981,  1.5217468 ]])

In [80]:
R = np.random.randn(10000)

In [81]:
R.mean()

-0.011306265922181572

In [82]:
np.mean(R)

-0.011306265922181572

In [83]:
R.var()

0.9898997541582685

In [85]:
R.std()

0.9949370604004398

In [86]:
np.sqrt(R.var())

0.9949370604004398

In [87]:
R = np.random.randn(10000, 3)

In [88]:
R.mean(axis=0)

array([-0.00070824,  0.01807059, -0.00844948])

In [89]:
R.mean(axis=1).shape

(10000,)

In [90]:
np.cov(R).shape

(10000, 10000)

In [91]:
np.cov(R.T)

array([[ 0.98744687,  0.00179858,  0.00349336],
       [ 0.00179858,  0.99941601, -0.01308482],
       [ 0.00349336, -0.01308482,  1.01112442]])

In [92]:
np.cov(R, rowvar=False)

array([[ 0.98744687,  0.00179858,  0.00349336],
       [ 0.00179858,  0.99941601, -0.01308482],
       [ 0.00349336, -0.01308482,  1.01112442]])

In [93]:
np.random.randint(0, 10, size=(3, 3))

array([[5, 5, 0],
       [5, 1, 0],
       [0, 0, 3]])

In [94]:
np.random.choice(10, size=(3, 3))

array([[2, 6, 5],
       [5, 3, 0],
       [2, 2, 0]])

In [ ]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(90, 100)
b = np.random.randn(100, 90)
T = 100

def slow_matrix_multiplication(a, b):

  a_rows, a_cols = a.shape
  b_rows, b_cols = b.shape
  result = np.zeros(10000).reshape(100, 100)
  for i in range(a_rows):
    total = 0
    for k in range(b_cols):
      for j in range(a_cols):
        total += a[i, j] * b[j, k]
      result[i, k] = total
  # print(result)
  return result
  #for e, f in zip(a, b):
  #  result += e*f
  #return result

t0 = datetime.now()
for t in range(T):
  slow_matrix_multiplication(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())